# Generated by Django 4.2.20 on 2025-03-19 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0004_location_event_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
