# Generated by Django 4.2.20 on 2025-03-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0008_event_cancel_limit_hours_event_max_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='signup_limit_hours',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
