# Generated by Django 4.2.20 on 2025-03-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0009_alter_event_signup_limit_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
